
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data

  p2go-celery-worker:
    build: .
    command: celery -A tasks worker --loglevel=warning
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  p2go-streamlit-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - p2go-celery-worker

volumes:
  redis:
    driver: local


